language: node_js
node_js:
  - node
cache:
  yarn
  # directories:
  #   - node_modules
install:
  - yarn ci
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
